receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"

exporters:
  jaeger:
    endpoint: "jaeger:16685"
    insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [jaeger]
