name: Go Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Check Go version
      run: go version

    - name: Clean Go module cache
      run: go clean -modcache

    - name: Tidy up Go modules
      run: go mod tidy

    - name: Clean up Go build
      run: go clean -cache -modcache -i -r

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...

